"""empty message

Revision ID: 66609fd7fe27
Revises: 
Create Date: 2021-01-09 17:18:42.643210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66609fd7fe27'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token1',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('token', sa.String(length=500), nullable=True),
    sa.Column('token_expires', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token1')
    # ### end Alembic commands ###
